parameters:
    bigfoot_import.client.class: 'Bigfoot\Bundle\ImportBundle\Services\Client'
    bigfoot_import.csvparser.class: 'Bigfoot\Bundle\ImportBundle\Services\CsvParser'
    bigfoot_import.xmlmapper.class: 'Bigfoot\Bundle\ImportBundle\Services\DataMapper\XmlMapper'
    bigfoot_import.datasourcetype.class: 'Bigfoot\Bundle\ImportBundle\Form\DataSourceType'
    bigfoot_import.data.loader.class: 'Bigfoot\Bundle\ImportBundle\Loader\ImportedDataLoader'
    bigfoot_import.data.manager.class: 'Bigfoot\Bundle\ImportBundle\Manager\ImportedDataManager'
    bigfoot_import.data.mapper.class: 'Bigfoot\Bundle\ImportBundle\Mapper\AbstractDataMapper'
    bigfoot_import.translation.queue.class: 'Bigfoot\Bundle\ImportBundle\Translation\DataTranslationQueue'
    bigfoot_import.data.mapper.factory.class: 'Bigfoot\Bundle\ImportBundle\Factory\MapperFactory'

services:
    bigfoot_import.client:
        class: '%bigfoot_import.client.class%'
    bigfoot_import.csvparser:
        class: '%bigfoot_import.csvparser.class%'
    bigfoot_import.xmlmapper:
        class: '%bigfoot_import.xmlmapper.class%'
        arguments:
            - '@doctrine.orm.entity_manager'
    form.type.protocol:
        class: Bigfoot\Bundle\ImportBundle\Form\ProtocolType
        arguments:
            - "%import.datasource.protocols%"
        tags:
            - { name: form.type, alias: protocol }
    bigfoot_bundle_importbundle_datasourcetype:
        class: '%bigfoot_import.datasourcetype.class%'
        arguments: ['@service_container']
        tags:
            - { name: form.type, alias: bigfoot_bundle_importbundle_datasourcetype}

    # Menu Subscriber
    bigfoot_import.subscriber.menu:
        class: Bigfoot\Bundle\ImportBundle\Subscriber\MenuSubscriber
        arguments:
            - '@security.token_storage'
        tags:
            - { name: kernel.event_subscriber }

    bigfoot_import.data.manager:
        class: %bigfoot_import.data.manager.class%
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@validator'
            - '@property_accessor'
            - '@bigfoot_import.translation.queue'
            - '@annotation_reader'
            - '@bigfoot_core.translation.repository'

    bigfoot_import.data.mapper:
        class: %bigfoot_import.data.mapper.class%
        abstract: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@bigfoot_import.translation.queue'

    bigfoot_import.translation.queue:
        class: %bigfoot_import.translation.queue.class%

    bigfoot_import.data.mapper.factory:
        class: %bigfoot_import.data.mapper.factory.class%
